import {compare} from './graph';
export type Hypothesis={id:string;asset:string;status:string;feature:string;rationale:string;existing:string;missing:string;experiment:string;falsifier:string;sources:string[];edgeIds:string[]};
const templates=[
 {id:'cholesterol-assay',asset:'Filipin imaging + cholesterol pulse–chase',status:'Reusable research asset',feature:'chol-export',rationale:'Both disease graphs contain impaired lysosomal cholesterol clearance. Static staining should be paired with a flux measurement.',existing:'Filipin is used in NPC assessment. SPG11 human neurons already show abnormal cholesterol localization. [S03, S09]',missing:'A matched, blinded comparison linking cholesterol clearance to SPG11 axonal survival is not established by this snapshot.',experiment:'Compare SPG11-mutant, NPC1-mutant and isogenic-corrected cortical neurons across ≥3 independent differentiations. After an LDL-cholesterol pulse, quantify lysosomal clearance over time, filipin–LAMP1 overlap, axonal transport and viability. Blind image analysis and preregister the clearance endpoint.',falsifier:'If SPG11 cells have normal clearance kinetics or improved localization without improved axonal function, cholesterol retention alone is insufficient.',sources:['S03','S06','S09']},
 {id:'cyclodextrin',asset:'HPβCD as an experimental cholesterol-mobilizing probe',status:'Exploratory transfer',feature:'chol-storage',rationale:'The graphs converge on lysosomal cholesterol accumulation, motivating a controlled cellular probe experiment.',existing:'HPβCD has NPC preclinical and human-study evidence. An early open-label study reported hearing loss and cannot establish efficacy. [S14, S16, S22]',missing:'No direct SPG11 HPβCD rescue evidence was identified in the sources curated here. This is not proof that it has never been tested.',experiment:'Apply a concentration-response series to SPG11 and NPC1 neurons with vehicle, isogenic correction and LXR-agonist controls. Quantify cholesterol flux, lysosomal tubulation, axon transport and viability. Require functional rescue independent of cytotoxic membrane cholesterol depletion before further work.',falsifier:'Lower filipin signal with impaired viability, unchanged transport or no recovery of lysosomal recycling argues against useful rescue.',sources:['S06','S09','S14','S16','S22']},
 {id:'lxr-rescue',asset:'LXR agonists as a SPG11 rescue benchmark',status:'Already tested in SPG11 cells',feature:'chol-homeostasis',rationale:'A cholesterol-homeostasis connection provides a shared comparison axis; SPG11 rescue already exists and should serve as a benchmark.',existing:'GW3965 and RGX104 improved cholesterol distribution and axonal phenotypes in SPG11-deficient human neurons. This is preclinical evidence. [S09]',missing:'Clinical benefit, CNS exposure, safety and efficacy across patient genotypes remain unresolved.',experiment:'Replicate the published phenotype in patient-derived neurons and corrected controls. Compare LXR activation with HPβCD using matched exposure and lipid-flux endpoints. Measure lysosome regeneration and axonal survival to distinguish bypass from correction.',falsifier:'A response restricted to one engineered cell line, or lipid redistribution without durable axonal benefit, weakens generalizability.',sources:['S06','S09']},
 {id:'substrate',asset:'Substrate reduction + lipidomics / NfL',status:'Human negative evidence matters',feature:'gsl-metabolism',rationale:'Glycosphingolipid handling is shared, but drug response requires independent evidence in SPG11.',existing:'Miglustat has already undergone a SPG11 phase II study with little neuromotor impact and no significant plasma lipid-profile change. Venglustat and St3gal5 knockdown showed preclinical benefits. [S10, S11, S15]',missing:'An effective human SPG11 intervention, adequate CNS target engagement and a validated surrogate endpoint remain unproven.',experiment:'Before another efficacy trial, compare exposure and ganglioside reduction in SPG11 patient-derived neurons. Pair lipidomics with axonal function and extracellular NfL. Use miglustat as the tested comparator and genetic substrate reduction as a mechanistic control.',falsifier:'Biochemical target engagement without axonal protection would argue against lipid reduction as a sufficient therapeutic strategy.',sources:['S07','S10','S11','S15']}
];
export function hypotheses():Hypothesis[]{
 const c=compare('spg','npc');
 return templates.filter(t=>c.shared.some(f=>f.id===t.feature)).map(t=>{const f=c.shared.find(f=>f.id===t.feature)!;return {...t,edgeIds:[...f.pathA,...f.pathB]}});
}
export const caveats={
 gm2:[{title:'One blocked reaction, distinct enzyme defects',text:'HEXA affects the α subunit; HEXB affects the β subunit and reduces both HEX A and HEX B. Sandhoff therefore has additional substrate and systemic consequences.',sources:['S01','S02']},{title:'Shared biology does not mean identical clinical courses',text:'Onset, residual activity and phenotype vary. This control tests mechanistic recovery, not interchangeable prognosis or treatments.',sources:['S01','S02']}],
 lysosomal:[{title:'Different primary defects',text:'NPC1/2 disrupt lipid transport. GBA1 disrupts enzymatic glucosylceramide degradation. The convergence is downstream.',sources:['S03','S23']},{title:'Autophagy findings depend on the model',text:'Gaucher fibroblasts had normal Beclin-1 and LC3-II in one comparison, while Gba-deficient neurons and astrocytes showed quality-control defects in another.',sources:['S12','S13']},{title:'Do not generalize neuronopathic findings to type 1',text:'Gaucher types 2/3 involve primary neurological disease. Type 1 has a different clinical pattern.',sources:['S04']}],
 exploratory:[{title:'Convergent phenotype, different machinery',text:'Spatacsin contributes to lysosomal recycling and reformation; NPC1/2 directly support cholesterol export. A shared storage phenotype does not establish a common initiating defect.',sources:['S06','S08','S21']},{title:'A relevant human trial was disappointing',text:'The SPG11 miglustat study did not show convincing neuromotor benefit or significant plasma lipid-profile changes. Its short, uncontrolled design also limits the conclusions.',sources:['S10','S15']},{title:'Timing and neuronal vulnerability remain unresolved',text:'Cell-model rescue does not establish benefit in patients. Disease stage, vulnerable neurons, genotype and exposure could change the response.',sources:['S05','S09','S10']},{title:'Autophagy is not a single interchangeable target',text:'NPC fibroblast evidence and SPG11 lysosome-reformation defects concern different cellular contexts and stages. A generic increase in autophagy should not be assumed beneficial.',sources:['S08','S12']}]
};
export function patientExplanation(id:string){
 if(id==='gm2')return {known:'Both conditions block breakdown of GM2, a fatty material that accumulates in nerve cells. This is a well-established biological relationship.',uncertain:'The genes, enzyme pattern and effects outside the brain differ. Similar biology does not predict the same course for every person.',meaning:'Researchers can share biochemical tests and some study approaches, while checking each disease separately.',sources:['S01','S02','S17']};
 if(id==='lysosomal')return {known:'Both involve lysosomes, the small compartments that process and recycle materials inside cells. Fats accumulate, although the original faults and stored fats differ.',uncertain:'Effects on nerve cells and recycling vary by disease and model. Many people with Gaucher type 1 do not have the primary neurological disease seen in types 2 and 3.',meaning:'Shared laboratory methods may help researchers study how disturbed fat handling harms cells.',sources:['S03','S04','S12','S13']};
 return {known:'In laboratory SPG11 models, cholesterol becomes trapped in lysosomes. NPC also causes problems moving cholesterol out of these compartments.',uncertain:'The proteins do different jobs. This research link does not mean the diseases are equivalent or that NPC medicines will help SPG11. Miglustat has already been studied in SPG11 without convincing clinical benefit.',meaning:'NPC research may offer useful tests and experimental tools. Any proposed drug transfer needs its own evidence of benefit and safety in SPG11.',sources:['S06','S09','S10','S15']};
}
