/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityExploreRouteImport } from './routes/community.explore'
import { Route as CommunityPatientsRouteImport } from './routes/community.patients'
import { Route as CommunityResearchRouteImport } from './routes/community.research'
import { Route as CommunityShareRouteImport } from './routes/community.share'
import { Route as CommunityCircleCircleIdRouteImport } from './routes/community.circle.$circleId'
import { Route as MapPairPairIdRouteImport } from './routes/map_.pair.$pairId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityExploreRoute = CommunityExploreRouteImport.update({
  id: '/community/explore',
  path: '/community/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPatientsRoute = CommunityPatientsRouteImport.update({
  id: '/community/patients',
  path: '/community/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityResearchRoute = CommunityResearchRouteImport.update({
  id: '/community/research',
  path: '/community/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityShareRoute = CommunityShareRouteImport.update({
  id: '/community/share',
  path: '/community/share',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCircleCircleIdRoute = CommunityCircleCircleIdRouteImport.update({
  id: '/community/circle/$circleId',
  path: '/community/circle/$circleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapPairPairIdRoute = MapPairPairIdRouteImport.update({
  id: '/map_/pair/$pairId',
  path: '/map/pair/$pairId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/community/explore': typeof CommunityExploreRoute
  '/community/patients': typeof CommunityPatientsRoute
  '/community/research': typeof CommunityResearchRoute
  '/community/share': typeof CommunityShareRoute
  '/community/': typeof CommunityIndexRoute
  '/community/circle/$circleId': typeof CommunityCircleCircleIdRoute
  '/map/pair/$pairId': typeof MapPairPairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/community/explore': typeof CommunityExploreRoute
  '/community/patients': typeof CommunityPatientsRoute
  '/community/research': typeof CommunityResearchRoute
  '/community/share': typeof CommunityShareRoute
  '/community': typeof CommunityIndexRoute
  '/community/circle/$circleId': typeof CommunityCircleCircleIdRoute
  '/map/pair/$pairId': typeof MapPairPairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/journey': typeof JourneyRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/community/explore': typeof CommunityExploreRoute
  '/community/patients': typeof CommunityPatientsRoute
  '/community/research': typeof CommunityResearchRoute
  '/community/share': typeof CommunityShareRoute
  '/community/': typeof CommunityIndexRoute
  '/community/circle/$circleId': typeof CommunityCircleCircleIdRoute
  '/map_/pair/$pairId': typeof MapPairPairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/journey'
    | '/map'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/community/explore'
    | '/community/patients'
    | '/community/research'
    | '/community/share'
    | '/community/'
    | '/community/circle/$circleId'
    | '/map/pair/$pairId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/journey'
    | '/map'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/community/explore'
    | '/community/patients'
    | '/community/research'
    | '/community/share'
    | '/community'
    | '/community/circle/$circleId'
    | '/map/pair/$pairId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/journey'
    | '/map'
    | '/profile'
    | '/resources'
    | '/settings'
    | '/community/explore'
    | '/community/patients'
    | '/community/research'
    | '/community/share'
    | '/community/'
    | '/community/circle/$circleId'
    | '/map_/pair/$pairId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JourneyRoute: typeof JourneyRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  CommunityExploreRoute: typeof CommunityExploreRoute
  CommunityPatientsRoute: typeof CommunityPatientsRoute
  CommunityResearchRoute: typeof CommunityResearchRoute
  CommunityShareRoute: typeof CommunityShareRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityCircleCircleIdRoute: typeof CommunityCircleCircleIdRoute
  MapPairPairIdRoute: typeof MapPairPairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/explore': {
      id: '/community/explore'
      path: '/community/explore'
      fullPath: '/community/explore'
      preLoaderRoute: typeof CommunityExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/patients': {
      id: '/community/patients'
      path: '/community/patients'
      fullPath: '/community/patients'
      preLoaderRoute: typeof CommunityPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/research': {
      id: '/community/research'
      path: '/community/research'
      fullPath: '/community/research'
      preLoaderRoute: typeof CommunityResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/share': {
      id: '/community/share'
      path: '/community/share'
      fullPath: '/community/share'
      preLoaderRoute: typeof CommunityShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/circle/$circleId': {
      id: '/community/circle/$circleId'
      path: '/community/circle/$circleId'
      fullPath: '/community/circle/$circleId'
      preLoaderRoute: typeof CommunityCircleCircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map_/pair/$pairId': {
      id: '/map_/pair/$pairId'
      path: '/map/pair/$pairId'
      fullPath: '/map/pair/$pairId'
      preLoaderRoute: typeof MapPairPairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JourneyRoute: JourneyRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  CommunityExploreRoute: CommunityExploreRoute,
  CommunityPatientsRoute: CommunityPatientsRoute,
  CommunityResearchRoute: CommunityResearchRoute,
  CommunityShareRoute: CommunityShareRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityCircleCircleIdRoute: CommunityCircleCircleIdRoute,
  MapPairPairIdRoute: MapPairPairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
